AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '*.gemspec'

Layout/LineLength:
  Max: 120


Style/FormatStringToken:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ParameterLists:
  Max: 6

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'
